<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE j8583-config [
<!ELEMENT j8583-config ( header+, template+, parse+ ) >

<!ELEMENT header ( #PCDATA ) >
<!ATTLIST header type NMTOKEN #REQUIRED >

<!ELEMENT template ( field+ ) >
<!ATTLIST template type NMTOKEN #REQUIRED >

<!ELEMENT parse ( field+ ) >
<!ATTLIST parse type NMTOKEN #REQUIRED >

<!ELEMENT field ( #PCDATA ) >
<!ATTLIST field num NMTOKEN #REQUIRED >
<!ATTLIST field length NMTOKEN #IMPLIED >
<!ATTLIST field type ( ALPHA | NUMERIC | AMOUNT | DATE10 | DATE4 | DATE_EXP | TIME | LLVAR | LLLVAR ) #REQUIRED >
	]>
<j8583-config>

<!-- These are the ISO headers to be prepended to the message types specified -->
<header type="0200">ISO015000050</header>
<header type="0210">ISO015000055</header>
<header type="0400">ISO015000050</header>
<header type="0410">ISO015000055</header>
<header type="0800">ISO015000015</header>
<header type="0810">ISO015000015</header>

<!-- The client example uses this to create requests -->
<template type="0200">
	<field num="4" type="ALPHA" length="12" >000000000000</field>
	<field num="32" type="LLVAR">2222222222</field>
	<field num="33" type="LLVAR">2222222222</field>
</template>

<template type="0400">
	<field num="4" type="ALPHA" length="12" >000000000000</field>
	<field num="32" type="LLVAR">2222222222</field>
	<field num="33" type="LLVAR">2222222222</field>
</template>

<template type="0420">
	<field num="4" type="ALPHA" length="12" >000000000000</field>
	<field num="32" type="LLVAR">2222222222</field>
	<field num="33" type="LLVAR">2222222222</field>
</template>

<template type="0800">
	<field num="70" type="ALPHA" length="3" >001</field>
</template>

<!-- The server example uses this to create the responses
	we only need a few fields because the rest are copied from the request -->
<template type="0210">
	<field num="60" type="LLLVAR">Fixed data from template</field>
	<field num="70" type="ALPHA" length="3">ABC</field>
	<field num="90" type="ALPHA" length="42">Field of length 42</field>
	<field num="100" type="LLVAR">Fixed field</field>
	<field num="102" type="LLVAR">Another fixed field</field>
	<field num="126" type="LLLVAR">...and yet another fixed field.</field>
</template>

<!-- The server example uses this to read the requests -->
<parse type="0200">
	<field num="2" type="LLVAR" />
	<field num="3" type="ALPHA" length="6"/>
	<field num="4" type="AMOUNT" />
	<field num="7" type="DATE10" />
	<field num="10" type="ALPHA" length="8" />
	<field num="11" type="NUMERIC" length="6" />
	<field num="12" type="TIME" />
	<field num="13" type="DATE4" />
	<field num="14" type="DATE_EXP" />
	<field num="15" type="DATE4" />
	<field num="18" type="ALPHA" length="4"/>
	<field num="32" type="LLVAR" />
	<field num="33" type="LLVAR" />
	<field num="37" type="NUMERIC" length="12" />
	<field num="41" type="ALPHA" length="8" />
	<field num="42" type="ALPHA" length="15" />
	<field num="43" type="ALPHA" length="40" />
	<field num="48" type="LLLVAR" />
	<field num="49" type="ALPHA" length="3" />
	<field num="52" type="ALPHA" length="16" />
	<field num="60" type="LLLVAR" />
	<field num="62" type="LLLVAR" />
	<field num="63" type="LLLVAR" />
	<field num="102" type="LLVAR" />
	<field num="103" type="LLVAR" />
	<field num="120" type="LLLVAR" />
	<field num="127" type="LLLVAR" />
</parse>
<parse type="0800">
	<field num="7" type="DATE10" />
	<field num="11" type="NUMERIC" length="6" />
	<field num="15" type="DATE4" />
	<field num="32" type="LLVAR" />
	<field num="70" type="ALPHA" length="3" />
</parse>
<!-- The client example uses this to read the responses -->
<parse type="0210">
	<field num="2" type="LLVAR" />
	<field num="3" type="ALPHA" length="6"/>
	<field num="4" type="AMOUNT" />
	<field num="7" type="DATE10" />
	<field num="10" type="ALPHA" length="8" />
	<field num="11" type="NUMERIC" length="6" />
	<field num="12" type="TIME" />
	<field num="13" type="DATE4" />
	<field num="14" type="DATE_EXP" />
	<field num="15" type="DATE4" />
	<field num="18" type="ALPHA" length="4"/>
	<field num="28" type="ALPHA" length="9" />
	<field num="32" type="LLVAR" />
	<field num="33" type="LLVAR" />
	<field num="37" type="NUMERIC" length="12" />
	<field num="39" type="ALPHA" length="2" />
	<field num="41" type="ALPHA" length="8" />
	<field num="42" type="ALPHA" length="15" />
	<field num="43" type="ALPHA" length="40" />
	<field num="48" type="LLLVAR" />
	<field num="49" type="ALPHA" length="3" />
	<field num="52" type="ALPHA" length="16" />
	<field num="60" type="LLLVAR" />
	<field num="62" type="LLLVAR" />
	<field num="63" type="LLLVAR" />
	<field num="102" type="LLVAR" />
	<field num="103" type="LLVAR" />
	<field num="120" type="LLLVAR" />
	<field num="127" type="LLLVAR" />
</parse>

<parse type="0410">
	<field num="2" type="LLVAR" />
	<field num="3" type="ALPHA" length="6"/>
	<field num="4" type="AMOUNT" />
	<field num="7" type="DATE10" />
	<field num="11" type="NUMERIC" length="6" />
	<field num="12" type="TIME" />
	<field num="13" type="DATE4" />
	<field num="14" type="DATE_EXP" />
	<field num="15" type="DATE4" />
	<field num="18" type="ALPHA" length="4"/>
	<field num="32" type="LLVAR" />
	<field num="33" type="LLVAR" />
	<field num="37" type="NUMERIC" length="12" />
	<field num="39" type="ALPHA" length="2" />
	<field num="41" type="ALPHA" length="8" />
	<field num="42" type="ALPHA" length="15" />
	<field num="43" type="ALPHA" length="40" />
	<field num="48" type="LLLVAR" />
	<field num="49" type="ALPHA" length="3" />
	<field num="52" type="ALPHA" length="16" />
	<field num="62" type="LLLVAR" />
	<field num="63" type="LLLVAR" />
	<field num="90" type="ALPHA" length="42" />
	<field num="102" type="LLVAR" />
	<field num="103" type="LLVAR" />
	<field num="120" type="LLLVAR" />
	<field num="127" type="LLLVAR" />
</parse>

<parse type="0430">
	<field num="2" type="LLVAR" />
	<field num="3" type="ALPHA" length="6"/>
	<field num="4" type="AMOUNT" />
	<field num="7" type="DATE10" />
	<field num="11" type="NUMERIC" length="6" />
	<field num="12" type="TIME" />
	<field num="13" type="DATE4" />
	<field num="14" type="DATE_EXP" />
	<field num="15" type="DATE4" />
	<field num="18" type="ALPHA" length="4"/>
	<field num="32" type="LLVAR" />
	<field num="33" type="LLVAR" />
	<field num="37" type="NUMERIC" length="12" />
	<field num="39" type="ALPHA" length="2" />
	<field num="41" type="ALPHA" length="8" />
	<field num="42" type="ALPHA" length="15" />
	<field num="43" type="ALPHA" length="40" />
	<field num="48" type="LLLVAR" />
	<field num="49" type="ALPHA" length="3" />
	<field num="52" type="ALPHA" length="16" />
	<field num="62" type="LLLVAR" />
	<field num="63" type="LLLVAR" />
	<field num="90" type="ALPHA" length="42" />
	<field num="102" type="LLVAR" />
	<field num="103" type="LLVAR" />
	<field num="120" type="LLLVAR" />
	<field num="127" type="LLLVAR" />
</parse>

<parse type="0810">
	<field num="7" type="DATE10" />
	<field num="11" type="NUMERIC" length="6" />
	<field num="15" type="DATE4" />
	<field num="32" type="LLVAR" />
	<field num="39" type="ALPHA" length="2" />
	<field num="48" type="LLLVAR" />
	<field num="70" type="ALPHA" length="3" />
</parse>

</j8583-config>
